### PR TITLE
myst-parser 0.15.2, add maintainers

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- includes #34
- blocks https://github.com/conda-forge/myst-nb-feedstock/pull/4
- adds @conda-forge/jupyter-book (i accept on our behalf)

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/myst-parser ready for review

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
the requirements should directly replicate those found in the main repo's setup.cfg

**Comment by choldgraf** [comment]
I think that the commit I just made does that (at least, reverts back to `~=`. I agree it'll be easier to maintain and keep track of dep upgrades if we use the same syntax

**Comment by dopplershift** [comment]
@bollwyvl Can we close this one out? Or is there stuff left to salvage here?

**Pull request closed without merging**
